package Package1;


import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Book_Issue.java
 *
 * Created on Jun 12, 2017, 4:01:30 PM
 */

/**
 *
 * @author Kartik Tyagi
 */
public class Book_Issue extends javax.swing.JFrame {

    /** Creates new form Book_Issue */
    public Book_Issue() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(496, 605));
        setResizable(false);
        getContentPane().setLayout(null);

        jSeparator1.setFont(new java.awt.Font("Tahoma", 1, 18));
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 60, 490, 20);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24));
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Issue A Book");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(200, 20, 140, 40);

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 14));
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Library Card Number :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 80, 150, 30);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(230, 80, 230, 30);

        jList1.setModel(new DefaultListModel());
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 120, 200, 360);

        jButton1.setFont(new java.awt.Font("Cambria", 1, 18));
        jButton1.setText("View Book Records");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(260, 130, 200, 40);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Package1/images/home 1.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(30, 490, 90, 80);

        jButton3.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jButton3.setText("Generate Report");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(280, 510, 180, 50);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(240, 200, 240, 280);

        jButton4.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jButton4.setText("<<Back<<");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(130, 510, 140, 50);

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Package1/images/person-sitting-on-book-shelf-in-library.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-280, 0, 790, 780);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
Main_Page ob=new Main_Page();
ob.setVisible(true);
this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    DefaultListModel l=(DefaultListModel)(jList1.getModel());
    l.clear();
    jTextArea1.setText("");
       try
       {
           Class.forName("java.sql.Driver");
           Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost/library","root","");
           Statement stmt=(Statement)con.createStatement();
           Statement stmt1=(Statement)con.createStatement();
           String query="select accession_number from book_information";
           ResultSet rs=stmt.executeQuery(query);
           ResultSet rs1=stmt1.executeQuery(query);
           rs1.first();
           String k=rs1.getString(1);
              while(rs.next())
              {
                 String a=rs.getString(1);
                    if(a.isEmpty())
                    {
                       JOptionPane.showMessageDialog(this,"No records to display");
                       break;
                    }
                 l.addElement(a);
              }
           stmt.close();
           con.close();
       }
       catch(Exception e)
       {
           if(e.getMessage().equals("Illegal operation on empty result set."))
           {
              JOptionPane.showMessageDialog(this,"No records to display");
           }
           else
           {
              JOptionPane.showMessageDialog(this,e.getMessage());
           }
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    int count=1;
    if(jTextField1.getText().equals(""))
    {
       JOptionPane.showMessageDialog(this,"Library Card Number Needed");
       int s=JOptionPane.showConfirmDialog(this,"Are you registered?","Confirming Registration",JOptionPane.YES_NO_OPTION);
         if(s==1)
         {
            JOptionPane.showMessageDialog(this,"Opening Registration.....");
            register_new_visitor ob=new  register_new_visitor();
            ob.setVisible(true);
            this.dispose();
         }
        else
        {
            DefaultListModel l=(DefaultListModel)(jList1.getModel());
            l.clear();
        }
    }
    else if(jTextField1.getText().equals("mysql")==false)
    {
        if(jList1.getSelectedValue()==null)
        {
           JOptionPane.showMessageDialog(this,"No Record Selected");
        }
        else
        {
           int count1=0;
           String Lib=jTextField1.getText();
             try
             {
                Class.forName("java.sql.Driver");
                Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost/library","root","");
                Statement stmt=(Statement)con.createStatement();
                Statement stmtks=(Statement)con.createStatement();
                String s="select LibraryCard_Number from Registered_issuers";
                ResultSet rs=stmt.executeQuery(s);
                ResultSet rs12=stmtks.executeQuery(s);
                rs12.first();
                String kk=rs12.getString(1);
                   while(rs.next())
                   {
                      String a1=rs.getString(1);
                         if(Lib.equals(a1))
                         {
                            JOptionPane.showMessageDialog(this,"Registration Confirmed");
                            count1=2;
                            break;
                         }
                         else
                         {
                            count1 =1;
                            continue;
                         }
                   }
                           if(count1==1)
                           {
                              JOptionPane.showMessageDialog(this,"Not Registered");
                              jTextField1.setText("");
        DefaultListModel m=(DefaultListModel)(jList1.getModel());
        m.clear();
        int sk=JOptionPane.showConfirmDialog(this,"Would you like to register?","Confirming Registration",JOptionPane.YES_NO_OPTION);
    if(sk==0)
    {
        register_new_visitor ob=new  register_new_visitor();
        ob.setVisible(true);
        this.dispose();
        this.setEnabled(false);
    }
    }
    if(count1==2)
    {
       String k=jTextField1.getText();
    Object k1=jList1.getSelectedValue();
    try{
    Class.forName("java.sql.Driver");
    Connection con1=(Connection)DriverManager.getConnection("jdbc:mysql://localhost/library","root","");
    Statement stmt1=(Statement)con1.createStatement();
    String skk="insert into Transaction_records(LibraryCard_Number,Accession_Number,Date_of_Issue) values('"+k+"','"+k1+"',curdate());";
    String s1="select Record_Number from transaction_Records";
    int l=stmt.executeUpdate(skk);
    if(l==1)
    {
       JOptionPane.showMessageDialog(this,"Transaction Complete");
       count=0;
    }
    if(count==0)
    {
        try{
    Class.forName("java.sql.Driver");
    Connection conk=(Connection)DriverManager.getConnection("jdbc:mysql://localhost/library","root","");
    Statement stmtk=(Statement)conk.createStatement();
    String sql="update book_information set stock_available = 0 where Accession_number = '"+k1+"';";
    stmtk.executeUpdate(sql);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }
    ResultSet rs1=stmt1.executeQuery(s1);
    int ka=0;
    int counter=0;
    while(rs1.next())
    {
    counter++;
    }
    ka=counter;
    JOptionPane.showMessageDialog(this,"Transaction Number: "+ka);
jTextArea1.setText("");
jTextArea1.append("~ ~ ~ ~ Transaction Record ~ ~ ~ ~\n\n");
jTextArea1.append("Library Card Number: "+k+"\n");
jTextArea1.append("Book Issued: "+k1+"\n");
jTextArea1.append("Transaction Number: "+ka+"\n");
}

    catch(Exception e)
    {
        JOptionPane.showMessageDialog(this,e.getMessage());
    }
}
    }
catch(Exception e1)
{
     if(e1.getMessage().equals("Illegal operation on empty result set."))
     {
       JOptionPane.showMessageDialog(this,"Library Card not registered");
       jTextField1.setText("");
       DefaultListModel m=(DefaultListModel)(jList1.getModel());
       m.clear();
       int sk=JOptionPane.showConfirmDialog(this,"Would you like to register?","Confirming Registration",JOptionPane.YES_NO_OPTION);
         if(sk==0)
         {
            register_new_visitor ob=new  register_new_visitor();
            ob.setVisible(true);
            this.dispose();
            this.setEnabled(false);
         }
        }
     else
     {
    JOptionPane.showMessageDialog(this, e1.getMessage());
}
}
        }
}
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
Transactions ob=new Transactions();
ob.setVisible(true);
this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Book_Issue().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

}
