/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * database_updation.java
 *
 * Created on Jun 15, 2017, 2:52:23 PM
 */

package Package1;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import javax.swing.JOptionPane;

/**
 *
 * @author Kartik Tyagi
 */
public class database_updation extends javax.swing.JFrame {

    /** Creates new form database_updation */
    public database_updation() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(468, 420));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Update Databases");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(150, 20, 190, 50);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 80, 580, 30);

        jButton1.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jButton1.setText("Update Book Records");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 110, 260, 50);

        jButton2.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jButton2.setText("Update Visitors Records");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(20, 210, 260, 50);

        jButton3.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jButton3.setText("Reset Database");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(20, 310, 260, 50);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Package1/images/home 1.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(340, 180, 90, 80);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Package1/images/Filoli-Library-Room-11.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-140, -10, 670, 530);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
Main_Page ob=new Main_Page();
ob.setVisible(true);
this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
update_book_records ob=new update_book_records();
ob.setVisible(true);
this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
update_visitors_record ob=new update_visitors_record();
ob.setVisible(true);
this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
try
{        String s=JOptionPane.showInputDialog(this,"Enter Administrator code :");
if(s.equals("KT149209"))
{
    int i=JOptionPane.showConfirmDialog(this,"Do you wish to delete all records?","Reset Data",JOptionPane.YES_NO_OPTION);
    if(i==0)
    {
        try{
    Class.forName("java.sql.Driver");
    Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost/library","root","");
    Statement stmt=(Statement) con.createStatement();
    String s1="delete from transaction_records;";
            String s2="alter table transaction_records auto_increment=1;";
            String s3="delete from book_information";
            String s4="delete from disposed;";
            String s5="delete from registered_issuers";
            stmt.executeUpdate(s1);
            stmt.executeUpdate(s2);
            stmt.executeUpdate(s3);
            stmt.executeUpdate(s4);
            stmt.executeUpdate(s5);
            JOptionPane.showMessageDialog(this,"All data has been safely deleted");
            stmt.close();
            con.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }
    else
    {
        database_updation ob=new database_updation();
        ob.setVisible(true);
        this.dispose();
    }
}
else
{
    JOptionPane.showMessageDialog(this,"Incorrect Administrator code");
}
}
catch(Exception e)
{
    database_updation ob=new database_updation();
        ob.setVisible(true);
        this.dispose();
}
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new database_updation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

}
