/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * dispose_visitor_record.java
 *
 * Created on Jun 15, 2017, 9:33:21 PM
 */

package Package1;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Kartik Tyagi
 */
public class dispose_visitor_record extends javax.swing.JFrame {

    /** Creates new form dispose_visitor_record */
    public dispose_visitor_record() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(537, 480));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24));
        jLabel2.setText("Dispose A Visitor Record");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(240, 10, 290, 40);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 60, 550, 20);

        jList1.setModel(new DefaultListModel());
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(15, 80, 190, 360);

        jButton1.setFont(new java.awt.Font("Cambria", 1, 18));
        jButton1.setText("View Records");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(220, 90, 190, 40);

        jButton2.setFont(new java.awt.Font("Cambria", 1, 18));
        jButton2.setText("Dispose Record");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(220, 160, 190, 40);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Package1/images/home 1.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(430, 100, 80, 80);

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 14));
        jLabel3.setText("Name :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(220, 250, 90, 30);

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 14));
        jLabel4.setText("Phone No. :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(220, 310, 100, 30);

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 14));
        jLabel5.setText("Visits :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(220, 368, 60, 30);

        jTextField1.setEditable(false);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(310, 250, 210, 30);

        jTextField2.setEditable(false);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(310, 310, 210, 30);

        jTextField3.setEditable(false);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(310, 370, 210, 30);

        jButton4.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        jButton4.setText("<<<<<Back<<<<<");
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(240, 410, 250, 29);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Package1/images/11Fotolia_36167041_M.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -80, 570, 620);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
Main_Page ob=new Main_Page();
ob.setVisible(true);
this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
jButton2.setEnabled(true);
jTextField1.setText("");
jTextField2.setText("");
jTextField3.setText("");
DefaultListModel l=(DefaultListModel)(jList1.getModel());
l.clear();
try
{
   Class.forName("java.sql.Driver");
   Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost/library","root","");
   Statement stmt=(Statement)con.createStatement();
   Statement stmt1=(Statement)con.createStatement();
   String s="select LibraryCard_number from Registered_issuers order by LibraryCard_number asc;";
   ResultSet rs=stmt.executeQuery(s);
   ResultSet rs1=stmt1.executeQuery(s);
   rs1.first();
   String k=rs1.getString(1);
    while(rs.next())
    {
      String a=rs.getString(1);
      l.addElement(a);
    }
   rs.close();
   stmt.close();
   con.close();
}
catch(Exception e)
{
  if(e.getMessage().equals("Illegal operation on empty result set."))
  {
    JOptionPane.showMessageDialog(this,"No records to display");
  }
  else
  {
    JOptionPane.showMessageDialog(this,e.getMessage());
  }
}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
int count =0;
if(jList1.getSelectedValue()==null)
{
  JOptionPane.showMessageDialog(this,"No Record Present");
}
else
{
  try
  {
    Class.forName("java.sql.Driver");
    Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost/library","root","");
    Statement stmt=(Statement)con.createStatement();
    Object a1=jList1.getSelectedValue();
    String s1="select * from disposed;";
    ResultSet rs1=stmt.executeQuery(s1);
    int count1=0;
     while(rs1.next())
     {
       if(a1.equals(rs1.getString(2)))
       {
         count1=1;
       }
     }
      if(count1==1)
      {
        jButton2.setEnabled(false);
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        JOptionPane.showMessageDialog(this,"These records have been disposed");
      }
      else if(count1==0)
      {
        jButton2.setEnabled(true);
        String s="select Name_of_issuer,Phone_numbers from registered_issuers where LibraryCard_number ='"+a1+"';";
        ResultSet rs=stmt.executeQuery(s);
         while(rs.next())
         {
           String a=rs.getString(1);
           String b= rs.getString(2);
           jTextField1.setText(a);
           jTextField2.setText(b);
         }
        String a="select Record_Number from Transaction_records where LibraryCard_Number='"+a1+"';";
        ResultSet r1=stmt.executeQuery(a);
         while(r1.next())
         {
           count++;
         }
        int k=count;
         if(k==1)
         {
           jTextField3.setText(Integer.toString(k)+" visit");
         }
         else
         {
           jTextField3.setText(Integer.toString(k)+" visits");
         }
      }
    stmt.close();
    con.close();
  }
  catch(Exception e)
  {
    if(jList1.getSelectedValue()==null)
    {
      JOptionPane.showMessageDialog(this,"No Library Card Number Selected");
    }
    else
    {
      JOptionPane.showMessageDialog(this,e.getMessage());
    }
  }
}
    }//GEN-LAST:event_jList1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
Object d=jList1.getSelectedValue();
if(d==null)
{
  JOptionPane.showMessageDialog(this,"No Record Selected");
  jTextField3.setText("");
}
else
{
 try
 {
   Class.forName("java.sql.Driver");
   Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost/library","root","");
   Statement stmt=(Statement)con.createStatement();
   String s1="insert into disposed(LibraryCard_number) values('"+d+"');";
   int i=stmt.executeUpdate(s1);
    if(i==1)
    {
      JOptionPane.showMessageDialog(this,"Records have been safely disposed");
      jButton2.setEnabled(false);
    }
   stmt.close();
   con.close();
 }
 catch(Exception e)
 {
   JOptionPane.showMessageDialog(this,e.getMessage());
 }
}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
update_visitors_record ob=new update_visitors_record();
ob.setVisible(true);
this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dispose_visitor_record().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables

}
