/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * dispose_book_record.java
 *
 * Created on Jun 15, 2017, 9:33:06 PM
 */

package Package1;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Kartik Tyagi
 */
public class dispose_book_record extends javax.swing.JFrame {

    /** Creates new form dispose_book_record */
    public dispose_book_record() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(503, 488));
        setResizable(false);
        getContentPane().setLayout(null);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 60, 500, 20);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24));
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Dispose A Book Record");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(130, 10, 260, 50);

        jList1.setModel(new DefaultListModel());
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 80, 190, 360);

        jButton1.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jButton1.setText("View Records");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(220, 80, 170, 40);

        jButton2.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jButton2.setText("Dispose Record");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(220, 141, 170, 40);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Package1/images/home 1.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(400, 90, 90, 80);

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 14));
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Title :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(230, 230, 60, 30);

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 14));
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Author :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(230, 290, 60, 30);

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 14));
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("Genre :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(230, 350, 50, 30);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(310, 230, 180, 30);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(310, 290, 180, 30);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(310, 350, 180, 30);

        jButton4.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        jButton4.setText("<<<<<<Back<<<<<<");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(230, 410, 260, 29);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Package1/images/pile-of-old-books.jpg2.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 510, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
Main_Page ob=new Main_Page();
ob.setVisible(true);
this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
update_book_records ob=new update_book_records();
ob.setVisible(true);
this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
jButton2.setEnabled(true);
jTextField1.setText("");
jTextField2.setText("");
jTextField3.setText("");
DefaultListModel m=(DefaultListModel)(jList1.getModel());
m.clear();
 try
 {
    Class.forName("java.sql.Driver");
    Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost/library","root","");
    Statement stmt=(Statement) con.createStatement();
    Statement stmt1=(Statement) con.createStatement();
    String s="select accession_number from book_information order by Accession_number asc;";
    ResultSet rs=stmt.executeQuery(s);
    ResultSet rs1=stmt1.executeQuery(s);
    rs1.first();
    String k=rs1.getString(1);
     while(rs.next())
     {
       String a=rs.getString(1);
       m.addElement(a);
     }
    rs.close();
    stmt.close();
    con.close();
 }
 catch(Exception e)
 {
   if(e.getMessage().equals("Illegal operation on empty result set."))
   {
     JOptionPane.showMessageDialog(this,"No records to display");
   }
   else
   {
     JOptionPane.showMessageDialog(this,e.getMessage());
   }
 }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
Object d=jList1.getSelectedValue();
if(d==null)
{
  JOptionPane.showMessageDialog(this,"No Record Selected");
}
else
{
  try
  {
    Class.forName("java.sql.Driver");
    Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost/library","root","");
    Statement stmt=(Statement) con.createStatement();
    String s1="insert into disposed(Accession_number) values('"+d+"');";
    int i=stmt.executeUpdate(s1);
     if(i==1)
     {
        JOptionPane.showMessageDialog(this,"Records have been safely disposed");
        jButton2.setEnabled(false);
     }
    stmt.close();
    con.close();
  }
  catch(Exception e)
  {
    JOptionPane.showMessageDialog(this,e.getMessage());
  }
}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
jButton2.setEnabled(true);
try
{
   Class.forName("java.sql.Driver");
   Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost/library","root","");
   Statement stmt=(Statement) con.createStatement();
   Object a1=jList1.getSelectedValue();
   String s1="select * from disposed;";
   ResultSet rs1=stmt.executeQuery(s1);
   int count=0;
    while(rs1.next())
    {
      if(a1.equals(rs1.getString(1)))
      {
        count=1;
      }
    }
    if(count==1)
    {
      jTextField1.setText("");
      jTextField2.setText("");
      jTextField3.setText("");
      jButton2.setEnabled(false);
      JOptionPane.showMessageDialog(this,"These records have been disposed");
    }
    else if(count==0)
    {
      jButton2.setEnabled(true);
      String s="select Title,Author,Genre from book_information where accession_number ='"+a1+"';";
      ResultSet rs=stmt.executeQuery(s);
       while(rs.next())
       {
         String a=rs.getString(1);
         String b= rs.getString(2);
         String c= rs.getString(3);
         jTextField1.setText(a);
         jTextField2.setText(b);
         jTextField3.setText(c);
       }
    }
    stmt.close();
    con.close();
}
catch(Exception e)
{
  if(jList1.getSelectedValue()==null)
  {
    JOptionPane.showMessageDialog(this,"No book Selected");
  }
  else
  {
    JOptionPane.showMessageDialog(this,e.getMessage());
  }
}
    }//GEN-LAST:event_jList1MouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dispose_book_record().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables

}
