/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * record_archives.java
 *
 * Created on Jun 15, 2017, 2:29:47 PM
 */

package Package1;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kartik Tyagi
 */
public class record_archives extends javax.swing.JFrame {

    /** Creates new form record_archives */
    public record_archives() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(586, 590));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24));
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Record Archives");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(200, 10, 210, 50);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 60, 580, 20);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "S.No.", "Library Card No.", "Accession No.", "Issue Date", "Return Date", "Duration", "Fine"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getColumn(0).setMaxWidth(60);
        jTable1.getColumnModel().getColumn(3).setMaxWidth(90);
        jTable1.getColumnModel().getColumn(4).setMaxWidth(120);
        jTable1.getColumnModel().getColumn(5).setMaxWidth(70);
        jTable1.getColumnModel().getColumn(6).setMaxWidth(65);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 70, 550, 210);

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 14));
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Name Of Visitor :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 300, 107, 30);

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 14));
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Phone Number :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 340, 101, 50);

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 14));
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("Title Of Book :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 400, 120, 30);

        jLabel6.setFont(new java.awt.Font("Cambria", 1, 14));
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("Date Of Issue :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 450, 90, 30);

        jLabel7.setFont(new java.awt.Font("Cambria", 1, 14));
        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("Number Of Visits :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 500, 113, 30);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(160, 300, 180, 30);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(160, 350, 180, 30);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(160, 400, 180, 30);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(160, 450, 180, 30);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(160, 500, 180, 30);

        jButton1.setFont(new java.awt.Font("Cambria", 1, 18));
        jButton1.setText("View Records");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(380, 310, 180, 50);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Package1/images/home 1.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(470, 450, 90, 80);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Package1/images/new-york-public-library.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -10, 580, 590);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Main_Page ob = new Main_Page();
        ob.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    jTextField1.setText("");
    jTextField2.setText("");
    jTextField3.setText("");
    jTextField4.setText("");
    jTextField5.setText("");
    DefaultTableModel t = (DefaultTableModel)jTable1.getModel();
    int r=t.getRowCount();
    if(r>=0)
    {
      for(int i=0;i<r;i++)
      {
         t.removeRow(0);
      }
    }
      try
      {
        Class.forName("java.sql.Driver");
        Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost/library", "root","");
        Statement stmt=(Statement)con.createStatement();
        String query="Select Record_Number,LibraryCard_Number,Accession_Number, Date_of_issue,Date_of_return,Duration_of_issue,Fine_Charged from Transaction_Records";
        ResultSet rs = stmt.executeQuery(query);
          while (rs.next())
          {
            String a11, b, c, d, e, f, g;
            a11=rs.getString(1);
            b=rs.getString(2);
            c=rs.getString(3);
            d=rs.getString(4);
            e=rs.getString(5);
            f=rs.getString(6);
            g=rs.getString(7);
            t.addRow(new Object[]{a11, b, c, d, e, f, g});
          }
            if (t.getRowCount()==0)
            {
              JOptionPane.showMessageDialog(this, "No records to display.");
            }
        stmt.close();
        con.close();
      } 
      catch(Exception e)
      {
        JOptionPane.showMessageDialog(this, e.getMessage());
      }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
    int s=jTable1.getSelectedRow();
    s=s+1;
    int count=0,count1=0;
    try
    {
      Class.forName("java.sql.Driver");
      Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost/library", "root","");
      Statement stmt=(Statement)con.createStatement();
      Statement stmt1=(Statement)con.createStatement();
      String sa="select * from disposed";
      String s1="select LibraryCard_Number,Accession_number,Date_of_issue from Transaction_records where Record_number='" + s + "';";
      ResultSet rs=stmt.executeQuery(s1);
      rs.first();
      ResultSet rs1=stmt1.executeQuery(sa);
      String l, ac;
      String x, y, z;
      x=rs.getString(1);
      y=rs.getString(2);
         while(rs1.next())
         {
            l=rs1.getString(2);
            ac=rs1.getString(1);
              if(x.equals(l))
              {
                 jTextField1.setText("");
                 jTextField2.setText("");
                 jTextField3.setText("");
                 jTextField4.setText("");
                 jTextField5.setText("");
                 JOptionPane.showMessageDialog(this, "The information has been disposed");
                 count1 = 1;
                 break;
              }
              if(y.equals(ac))
              {
                 jTextField1.setText("");
                 jTextField2.setText("");
                 jTextField3.setText("");
                 jTextField4.setText("");
                 jTextField5.setText("");
                 JOptionPane.showMessageDialog(this, "The information has been disposed");
                 count1 = 1;
                break;
              }
         }
            if (count1 == 0)
            {
                Statement stmt2 = (Statement) con.createStatement();
                String s2 = "select LibraryCard_Number,Accession_number,Date_of_issue from Transaction_records where Record_number='" + s + "';";
                ResultSet rs3 = stmt2.executeQuery(s2);
                rs3.first();
                String x1=rs3.getString(1);
                String y1=rs3.getString(2);
                z=rs3.getString(3);
                String S="select Name_of_issuer,Phone_numbers,Title from Registered_issuers,Book_information"
                        + " where LibraryCard_Number = '" + x1 + "' && Accession_Number = '" + y1 + "';";
                ResultSet Rs=stmt2.executeQuery(S);
                String a,b,c;
                Rs.first();
                a=Rs.getString(1);
                b=Rs.getString(2);
                c=Rs.getString(3);
                jTextField1.setText(a);
                jTextField2.setText(b);
                jTextField3.setText(c);
                jTextField4.setText(z);
                String ak="select Record_Number from transaction_records where LibraryCard_Number='" + x + "';";
                ResultSet r1=stmt1.executeQuery(ak);
                while(r1.next())
                {
                  count++;
                }
                int k=count;
                if (k==1)
                {
                  jTextField5.setText(Integer.toString(k) + " visit");
                }
                else
                {
                  jTextField5.setText(Integer.toString(k) + " visits");
                }

            }
            stmt.close();
            con.close();
    } 
    catch(Exception e)
    {
       jTextField1.setText("");
       jTextField2.setText("");
       jTextField3.setText("");
       jTextField4.setText("");
       jTextField5.setText("");
       String sk;
       sk=e.getMessage();
       if(sk.equals("Illegal operation on empty result set."))
       {
          JOptionPane.showMessageDialog(this, "Book information has been disposed \n"
                        + "                            Or \n"
                        + "Issuer Information has been disposed");
       } 
       else
       {
          JOptionPane.showMessageDialog(this, e.getMessage());
       }
    }
    }//GEN-LAST:event_jTable1MouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new record_archives().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables

}
