package Package1;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * register_new_visitor.java
 *
 * Created on Jun 15, 2017, 1:52:39 PM
 */

/**
 *
 * @author Kartik Tyagi
 */
public class register_new_visitor extends javax.swing.JFrame {

    /** Creates new form register_new_visitor */
    public register_new_visitor() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(440, 530));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 14));
        jLabel2.setText("Name :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 90, 60, 30);

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 14));
        jLabel3.setText("Library Card Number :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 150, 141, 30);

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 14));
        jLabel4.setText("Phone Number:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 208, 98, 30);

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 14));
        jLabel5.setText("Address :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 280, 90, 30);

        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(200, 90, 170, 30);

        jTextField2.setEditable(false);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(200, 150, 170, 30);

        jTextField3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField3FocusLost(evt);
            }
        });
        getContentPane().add(jTextField3);
        jTextField3.setBounds(200, 210, 170, 30);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(200, 280, 170, 96);

        jButton1.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jButton1.setText("Register ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(60, 420, 160, 50);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Package1/images/home 1.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(270, 410, 90, 80);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(50, 70, 320, 20);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24));
        jLabel6.setText("Registration Form");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(120, 30, 210, 40);

        jButton3.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(60, 383, 160, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Package1/images/!!!!.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-10, 0, 450, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    Main_Page ob = new Main_Page();
    ob.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    jTextField1.setText("");
    jTextField2.setText("");
    jTextField3.setText("");
    jTextArea1.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    try
    {   
      Class.forName("java.sql.Driver");
      Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost/library","root","");
      Statement stmt=(Statement) con.createStatement();
      Statement stmt1=(Statement) con.createStatement();
      String s="select LibraryCard_Number from Registered_issuers";
      ResultSet rs=stmt1.executeQuery(s);
      ResultSet rs1=stmt.executeQuery(s);
      rs1.first();
      String k1=rs1.getString(1);
        while(rs.next())
        {
          if(rs.last())
          {
            String a=rs.getString(1);
            String a1=a.substring(1);
            int k=Integer.parseInt(a1);
            k=k+1;
             if(k<10)
             {
               jTextField2.setText("L0"+Integer.toString(k));
             }
             else
             {
               jTextField2.setText("L"+Integer.toString(k));
             }           
          }
        }
      stmt.close();
      con.close();
    }
    catch(Exception e2)
    {
      if(e2.getMessage().equals("Illegal operation on empty result set."))
      {
        jTextField2.setText("L01");
      }
      else
      {
        JOptionPane.showMessageDialog(null,e2.getMessage());
      }    
    }
    }//GEN-LAST:event_formWindowOpened

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
String s=jTextField1.getText();    
int l=s.length();
if(s.isEmpty()==false)
{
  for(int i=0;i<l;i++)
  {
    char ch=s.charAt(i);
      if(Character.isLetter(ch)==false)
      {
        if(ch==' ')
        {
           continue; 
        }
        JOptionPane.showMessageDialog(this,"Name must be in alphabets");
        jTextField1.setText("");
        break;
      }
  }
}
    }//GEN-LAST:event_jTextField1FocusLost

    private void jTextField3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField3FocusLost
String s=jTextField3.getText();    
int l=s.length();
if(l!=10)
{
  JOptionPane.showMessageDialog(this,"Incorrect Phone Number");
  jTextField3.setText("");
}
else
{
  if(s.isEmpty()==false)
  {
    for(int i=0;i<l;i++)
    {
      char ch=s.charAt(i);
       if(Character.isDigit(ch)==false)
       {
         JOptionPane.showMessageDialog(this,"Phone Number must be in digits");
         jTextField3.setText("");
         break;
       }
    }
  }
}
    }//GEN-LAST:event_jTextField3FocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String a1=jTextField1.getText();
String b=jTextField2.getText();
String c=jTextField3.getText();
String d=jTextArea1.getText();
if(a1.isEmpty()||c.isEmpty()||d.isEmpty())
{
  JOptionPane.showMessageDialog(this,"Information required");
}
else
{
  try
  {
    Class.forName("java.sql.Driver");
    Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost/library","root","");
    Statement stmt=(Statement) con.createStatement();
    String s="insert into Registered_issuers(Name_of_issuer,LibraryCard_Number,Phone_numbers,Address,Date_Registration) values ('"+a1+"','"+b+"','"+c+"','"+d+"',curdate());";
    int p=stmt.executeUpdate(s);
      if(p==1)
      { 
        JOptionPane.showMessageDialog(this,"Successful Registration");
        int i=JOptionPane.showConfirmDialog(this,"Would you like to issue a book?","Message",JOptionPane.YES_NO_OPTION);
         if(i==0)
         {
           Book_Issue ob= new Book_Issue();
           ob.setVisible(true);
           this.dispose();
         } 
         else if(i==1)
         {
           Main_Page ob= new Main_Page();
           ob.setVisible(true);
           this.dispose();
         }
      }
    stmt.close();
    con.close();
}
catch(Exception e)
{
  JOptionPane.showMessageDialog(this,e.getMessage());
}
}
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new register_new_visitor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables

}
