/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Return_Book.java
 *
 * Created on Jun 12, 2017, 4:01:54 PM
 */

package Package1;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Kartik Tyagi
 */
public class Return_Book extends javax.swing.JFrame {

    /** Creates new form Return_Book */
    public Return_Book() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(463, 475));
        setResizable(false);
        getContentPane().setLayout(null);

        jSeparator1.setFont(new java.awt.Font("Tahoma", 1, 24));
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 70, 460, 20);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24));
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Return Books");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(160, 20, 170, 40);

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 14));
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Library Card Number :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 110, 141, 30);

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 14));
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Book Number :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 170, 100, 30);

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 14));
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("Transaction Number :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 240, 138, 10);

        jLabel6.setFont(new java.awt.Font("Cambria", 1, 14));
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("Duration :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 380, 100, 40);

        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(210, 110, 230, 30);

        jTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField2FocusLost(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(210, 170, 230, 30);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(210, 230, 230, 30);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(140, 380, 150, 40);

        jButton1.setFont(new java.awt.Font("Cambria", 1, 18));
        jButton1.setText("Register");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(80, 290, 210, 60);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Package1/images/home 1.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(330, 290, 90, 80);

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Cambria", 1, 18));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("<<Back<<");
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(290, 390, 160, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Package1/images/376152628_249e3630c0_o.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-110, 0, 580, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
Main_Page ob=new Main_Page();
ob.setVisible(true);
this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
Transactions ob=new Transactions();
ob.setVisible(true);
this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String tno=jTextField3.getText();
String bookno=jTextField2.getText();
int c=0;
if(tno.isEmpty())
{
   JOptionPane.showMessageDialog(this,"Please enter a record number.");
}
else if(bookno.isEmpty())
{
   JOptionPane.showMessageDialog(this,"Please enter the book number.");
}
else if(tno.isEmpty()==false)
{
   try
   {
      Class.forName("java.sql.Driver");
      Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost/library","root","");
      Statement stmt=(Statement)con.createStatement();
      String query="Select date_of_return from transaction_records where record_number='"+tno+"';";
      ResultSet rs=stmt.executeQuery(query);
      String dor="";
      rs.first();
      dor=rs.getString(1);
        if(dor.isEmpty()==false)
        {
           JOptionPane.showMessageDialog(this,"This transaction has already been made.");
           jTextField2.setText("");
           jTextField3.setText("");
           jTextField1.setText("");
           jTextField4.setText("");
           c=0;
        }
   }
   catch(Exception e)
   {
      c=1;
   }
}
   if(c==1)
   {
      try
      {
         Class.forName("java.sql.Driver");
         Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost/library","root","");
         Statement stmt=(Statement)con.createStatement();
         Statement stmt1=(Statement)con.createStatement();
         Statement stmt2=(Statement)con.createStatement();
         String query1="Select accession_number from transaction_records where record_number='"+tno+"';";
         String query2="Update book_information set Stock_available = 1 where accession_number = '"+bookno+"';";
         String query3="Update Transaction_Records set Date_of_return = curdate() where Record_Number='"+tno+"';";
         ResultSet rs1=stmt2.executeQuery(query1);
         rs1.first();
         int count1=0;
         String acc=rs1.getString(1);
           if(bookno.equals(acc))
           {
             count1=1;
           }
           else
           {
              JOptionPane.showMessageDialog(this,"Incorrect Book Number.");
              jTextField2.setText("");
              jTextField3.setText("");
              jTextField1.setText("");
              jTextField4.setText("");
              count1=0;
           }
      if(count1==1)
      {
        int i=stmt.executeUpdate(query3);
        int count=0;
          if(i==1)
          {
            JOptionPane.showMessageDialog(this,"Registration Complete.");
            count=1;
          }
          else
          {
            JOptionPane.showMessageDialog(this,"Registration Failed.");
            count=0;
          }
          if(count==1)
          {
            stmt1.executeUpdate(query2);
          }
          else
          {
            JOptionPane.showMessageDialog(this,"No such record exists");
            jTextField3.setText("");
            jTextField2.setText("");
            jTextField1.setText("");
            jTextField4.setText("");
          }
        String query4="select DateDiff(Date_of_return, Date_of_issue) from Transaction_Records where Record_Number='"+tno+"';";
        ResultSet rs=stmt.executeQuery(query4);
        rs.first();
        String a=rs.getString(1);
        String a1=a+" days";
        jTextField4.setText(a+" days");
        String sa="update Transaction_Records set Duration_of_issue='"+a1+"' where Record_Number='"+tno+"';";
        stmt.executeUpdate(sa);
        String f;
          if(Integer.parseInt(a)>15)
          {
            double fine;
            fine=5*(Integer.parseInt(a)-15);
            f=Double.toString(fine)+" Rs";
          }
          else
          {
            f="0 Rs";
          }
        String sm="update Transaction_records set Fine_Charged='"+f+"' where Record_Number='"+tno+"';";
        stmt.executeUpdate(sm);
        stmt.close();
        con.close();
      }
      }
      catch(Exception e)
      {
         String a=e.getMessage();
         if(a.equals("Illegal operation on empty result set."))
         {
           JOptionPane.showMessageDialog(this,"No such record exists.");
           jTextField3.setText("");
           jTextField2.setText("");
           jTextField1.setText("");
           jTextField4.setText("");
         }
         else
         {
           JOptionPane.showMessageDialog(this,e.getMessage());
         }

      }
   }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
String s=jTextField1.getText();
try
{
    Class.forName("java.sql.Driver");
    Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost/library","root","");
    Statement stmt=(Statement)con.createStatement();
    String s1="select * from disposed;";
    ResultSet rs1=stmt.executeQuery(s1);
    int count=0;
       while(rs1.next())
       {
          if(s.equals(rs1.getString(2)))
          {
             count=1;
             break;
          }
       }
       if(count==1)
       {
          JOptionPane.showMessageDialog(this,"The Issuer records have been disposed");
          jTextField1.setText("");
       }
    stmt.close();
    con.close();
}
catch(Exception e)
{
    JOptionPane.showMessageDialog(this,e.getMessage());
}
    }//GEN-LAST:event_jTextField1FocusLost

    private void jTextField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusLost
String s=jTextField2.getText();
try
{
    Class.forName("java.sql.Driver");
    Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost/library","root","");
    Statement stmt=(Statement)con.createStatement();
    String s1="select * from disposed;";
    ResultSet rs1=stmt.executeQuery(s1);
    int count=0;
      while(rs1.next())
      {
         if(s.equals(rs1.getString(1)))
         {
            count=1;
            break;
         }
      }
      if(count==1)
      {
         JOptionPane.showMessageDialog(this,"The Book records have been disposed");
         jTextField2.setText("");
         jTextField1.setText("");
      }
    stmt.close();
    con.close();
}
catch(Exception e)
{
JOptionPane.showMessageDialog(this,e.getMessage());
}
    }//GEN-LAST:event_jTextField2FocusLost

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Return_Book().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables

}
