/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * View_Book.java
 *
 * Created on Jun 12, 2017, 3:19:21 PM
 */

package Package1;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Kartik Tyagi
 */
public class Search_Book_Records extends javax.swing.JFrame {

    /** Creates new form View_Book */
    public Search_Book_Records() {
        initComponents();
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jComboBox1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(559, 547));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel8.setFont(new java.awt.Font("Cambria", 1, 14));
        jLabel8.setForeground(new java.awt.Color(240, 240, 240));
        jLabel8.setText("Pick Genre                    (Optional)");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(230, 80, 200, 18);

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 14));
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Title :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(230, 190, 50, 20);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24));
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("List Of Books");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(220, 20, 210, 28);

        jSeparator1.setFont(new java.awt.Font("Tahoma", 1, 16));
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 60, 560, 20);

        jList1.setModel(new DefaultListModel());
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 80, 180, 410);

        jComboBox1.setModel(new DefaultComboBoxModel());
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(230, 110, 190, 30);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Package1/images/home 1.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(450, 70, 80, 80);

        jButton2.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jButton2.setText("View Records");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(260, 450, 240, 40);

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 14));
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Author :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(230, 240, 60, 18);

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 14));
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("Genre :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(230, 290, 60, 20);

        jLabel6.setFont(new java.awt.Font("Cambria", 1, 14));
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("Price :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(230, 340, 70, 20);

        jLabel7.setFont(new java.awt.Font("Cambria", 1, 14));
        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("Stock Available :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(230, 390, 104, 18);

        jTextField1.setEditable(false);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(360, 180, 180, 30);

        jTextField2.setEditable(false);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(360, 230, 180, 30);

        jTextField3.setEditable(false);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(360, 280, 180, 30);

        jTextField4.setEditable(false);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(360, 330, 180, 30);

        jTextField5.setEditable(false);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(360, 380, 180, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Package1/images/122.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -40, 560, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    Main_Page ob=new Main_Page();
    ob.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
    try
    {
       Class.forName("java.sql.Driver");
       Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost/library","root","");
       Statement stmt=(Statement)con.createStatement();
       Object l1=jList1.getSelectedValue();
       String query="select * from disposed;";
       ResultSet rs=stmt.executeQuery(query);
       int count=0;      
         if(rs.next())
         {   
             while(rs.next())
             {
                 if(l1.equals(rs.getString(1)))
                 {  
                    count=1;
                    break;
                 }
             }
         }
                if(count==1)
                {
                   JOptionPane.showMessageDialog(this,"These records have been disposed");
                   int i=JOptionPane.showConfirmDialog(this,"Do You wish to undispose them?","Question",JOptionPane.YES_NO_OPTION);
                      if(i==0)
                      {
                         Statement stmts=(Statement)con.createStatement();
                         String query1="Delete from disposed where accession_number='"+l1+"';";
                         stmts.executeUpdate(query1);
                         JOptionPane.showMessageDialog(this,"Records have been undisposed.");
                      }
                }
                if(count==0)
                {   
                    String query2="Select Title,Author,Genre,Price,Stock_Available from book_information where accession_number='"+l1+"';";
                    ResultSet rs1=stmt.executeQuery(query2);
                       while(rs1.next())
                       {
                          jTextField1.setText(rs1.getString(1));
                          jTextField2.setText(rs1.getString(2));
                          jTextField3.setText(rs1.getString(3));
                          jTextField4.setText(rs1.getString(4));
                          jTextField5.setText(rs1.getString(5));
                       }
                }
    stmt.close();
    con.close();
    }
    catch(Exception e)
    {
        if(jList1.getSelectedValue()==null)
        {
           JOptionPane.showMessageDialog(this,"No book Selected");
        }
        else
        {
           JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }
    }//GEN-LAST:event_jList1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
jTextField1.setText("");
jTextField2.setText("");
jTextField3.setText("");
jTextField4.setText("");
jTextField5.setText("");
DefaultListModel l=(DefaultListModel)jList1.getModel();
l.clear();
   try
   {
       Class.forName("java.sql.Driver");
       Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost/library","root","");
       Statement stmt=(Statement)con.createStatement();
       String val=(String)jComboBox1.getSelectedItem();
       String query="Select accession_number from book_information where Genre='"+val+"' order by Accession_number asc;";
       ResultSet rs=stmt.executeQuery(query);
           while(rs.next())
           {
              String accessno=rs.getString(1);
              l.addElement(accessno);
           }
       stmt.close();
       con.close();
   }
   catch(Exception e)
   {
       if(e.getMessage().equals("Illegal operation on empty result set."))
       {
            JOptionPane.showMessageDialog(this,"No records to display");
            int i=JOptionPane.showConfirmDialog(this,"Wish to add a book to your Library?","First Registration",JOptionPane.YES_NO_OPTION);
            if(i==0)
            {
                new_book_addition ob= new new_book_addition();
                ob.setVisible(true);
                this.dispose();
            }
            else
            {
                Search_Book_Records ob=new Search_Book_Records();
                ob.setVisible(true);
                this.dispose();
            }
       }
       else
       {
            JOptionPane.showMessageDialog(this,e.getMessage());
       }
   }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
DefaultComboBoxModel cb=(DefaultComboBoxModel)jComboBox1.getModel();
try
{
    Class.forName("java.sql.DriverManager");
    Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost/library","root","");
    Statement stmt=(Statement)con.createStatement();
    String query="Select distinct genre from book_information;";
    ResultSet rs=stmt.executeQuery(query);
    while(rs.next())
    {
       String genre=rs.getString(1);
       cb.addElement(genre);
    }
    stmt.close();
    con.close();
}
catch(Exception e)
{
    JOptionPane.showMessageDialog(this,e.getMessage());
}
    }//GEN-LAST:event_formWindowOpened

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Search_Book_Records().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables

}
