/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Sign_Up_Page.java
 *
 * Created on Jun 8, 2017, 12:56:02 PM
 */

package Package1;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import javax.swing.JOptionPane;

/**
 *
 * @author Kartik Tyagi
 */
public class Sign_Up_Page extends javax.swing.JFrame {
    /** Creates new form Sign_Up_Page */
    public Sign_Up_Page() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(451, 510));
        setName("frame 2"); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 20));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Library Accounts");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(150, 40, 150, 24);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("_________________________________________");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 50, 460, 30);

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 14));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Name :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 100, 80, 20);

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 14));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Phone Number :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 150, 110, 18);

        jLabel6.setFont(new java.awt.Font("Cambria", 1, 14));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Username :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 200, 70, 18);

        jLabel7.setFont(new java.awt.Font("Cambria", 1, 14));
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Password :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 250, 69, 18);

        jLabel8.setFont(new java.awt.Font("Cambria", 1, 14));
        jLabel8.setForeground(new java.awt.Color(240, 240, 240));
        jLabel8.setText("Confirm Password :");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(40, 300, 123, 18);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(210, 100, 190, 20);

        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField2KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(210, 150, 190, 20);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(210, 200, 190, 20);

        jButton1.setFont(new java.awt.Font("Cambria", 1, 14));
        jButton1.setText("SIGN UP");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(270, 370, 130, 40);
        getContentPane().add(jLabel9);
        jLabel9.setBounds(40, 420, 0, 0);

        jLabel10.setFont(new java.awt.Font("Cambria", 1, 14));
        jLabel10.setForeground(new java.awt.Color(240, 240, 240));
        jLabel10.setText("If you a registered user click");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(60, 450, 190, 20);

        jButton2.setFont(new java.awt.Font("Cambria", 1, 14));
        jButton2.setForeground(new java.awt.Color(0, 0, 204));
        jButton2.setText("Back To Login/SignIn");
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(220, 450, 210, 20);
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(210, 250, 190, 20);
        getContentPane().add(jPasswordField2);
        jPasswordField2.setBounds(210, 300, 190, 20);

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 14));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Package1/images/3.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-130, 0, 580, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
login_page ob=new login_page();
ob.setVisible(true);
this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String name,pno,uname,password,cpassword;
name=jTextField1.getText();
pno=jTextField2.getText();
uname=jTextField3.getText();
password=jPasswordField1.getText();
cpassword=jPasswordField2.getText();
if(name.equals("")||pno.equals("")||uname.equals("")||password.equals("")||cpassword.equals(""))
{
    JOptionPane.showMessageDialog(this,"Please enter the required information.");
}
else if(password.equals(cpassword)!=true)
{
    JOptionPane.showMessageDialog(this,"Password do not match.Please enter password again.");
    jPasswordField1.setText("");
    jPasswordField2.setText("");
}
else
{
    String ques=JOptionPane.showInputDialog(this,"Security Question. \n"+"Example:What is your favourite holiday destination.");
    String ans="";
    while(ques.equals(""))
    {
        ques=JOptionPane.showInputDialog(this,"Security Question. \n"+"Example:What is your favourite holiday destination?");
    }
       if(ques.equals("")==false)
       {
          ans=JOptionPane.showInputDialog(this,"Security Answer.");
          while(ans.equals(""))
          {
             ans=JOptionPane.showInputDialog(this,"Security Answer.");
          }
       }
          try
          {
             Class.forName("java.sql.Driver");
             Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost/library","root","");
             Statement stmt=(Statement)con.createStatement();
             String query="Insert into user_id values ('"+name+"','"+pno+"','"+uname+"','"+password+"','"+ques+"','"+ans+"');";
             int i=stmt.executeUpdate(query);
                if(i==1)
                {
                    JOptionPane.showMessageDialog(this, "You have been registered");
                    JOptionPane.showMessageDialog(this,"Your Administrator code is \n"+"KT149209");
                    Main_Page ob=new Main_Page();
                    ob.setVisible(true);
                    this.dispose();
                }
                else if(i==0)
                {
                    JOptionPane.showMessageDialog(this, "You could not be registered");
                }
             stmt.close();
             con.close();
          }
          catch(Exception e)
          {
             JOptionPane.showMessageDialog(this,"Sorry!Internal Error.");
          }
          /**catch(Exception e)
          {
             JOptionPane.showMessageDialog(this,"Sorry!Internal Error.");
          }*/
}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyTyped
char c=evt.getKeyChar();
if(c>='0'&&c<='9')
{

}
else
{
    evt.consume();
}
    }//GEN-LAST:event_jTextField2KeyTyped

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sign_Up_Page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables

}
